# Generated by Django 6.0.1 on 2026-01-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='billable_target',
            field=models.PositiveIntegerField(default=1600, help_text='Yearly billable hours target'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional biography'),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='office_location',
            field=models.CharField(default='Headquarters', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(default=list, help_text="List of technical skills e.g. ['IFRS', 'GAAP', 'Python']"),
        ),
    ]
