# Generated by Django 6.0.1 on 2026-01-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_avatar_url_user_billable_target_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
