# Generated by Django 6.0.1 on 2026-01-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.TextField(blank=True, help_text='Can be a URL or a Base64 encoded image string', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
    ]
