# Generated by Django 6.0.1 on 2026-01-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_avatar_url_alter_user_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
