# Generated by Django 6.0.1 on 2026-01-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='entity_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('LLC', 'Limited Liability Company'), ('CORP', 'Corporation'), ('PARTNERSHIP', 'Partnership'), ('NGO', 'Non-Profit')], default='LLC', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='fiscal_year_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.client'),
        ),
    ]
