# Generated by Django 6.0.1 on 2026-01-09 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_clientdocument_clientnote_engagement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.engagement'),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='crm.clientnote'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engagement',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='lead_auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagement',
            name='methodology',
            field=models.CharField(default='Standard Audit', help_text='e.g. GAAP, IFRS', max_length=100),
        ),
        migrations.AddField(
            model_name='engagement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EngagementTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'In Review'), ('DONE', 'Done')], default='PENDING', max_length=20)),
                ('is_milestone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.engagement')),
            ],
        ),
    ]
