# Generated by Django 6.0.1 on 2026-01-11 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_engagementtask_prepared_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='partner_rotation_due',
            field=models.DateField(help_text='Date when lead partner must rotate off', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='client',
            name='risk_rating',
            field=models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pbcrequest',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pbc_requests', to='crm.engagement'),
        ),
        migrations.AlterField(
            model_name='pbcrequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SUBMITTED', 'Submitted by Client'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Returned')], default='OPEN', max_length=20),
        ),
    ]
