# Generated by Django 6.0.1 on 2026-01-11 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_clientcontact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workpapers', to='crm.engagement'),
        ),
    ]
