# Generated by Django 6.0.1 on 2026-01-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_historicalclientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnote',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
