# Generated by Django 6.0.1 on 2026-01-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_clientnote_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='category',
            field=models.CharField(choices=[('GENERAL_LEDGER', 'General Ledger'), ('BANK_STATEMENT', 'Bank Statement'), ('TAX_RETURN', 'Tax Return'), ('PAYROLL', 'Payroll Records'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalclientdocument',
            name='category',
            field=models.CharField(choices=[('GENERAL_LEDGER', 'General Ledger'), ('BANK_STATEMENT', 'Bank Statement'), ('TAX_RETURN', 'Tax Return'), ('PAYROLL', 'Payroll Records'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
