# Generated by Django 6.0.1 on 2026-01-19 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_vendor_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
